### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by venuv** [vlukiyanov/pt-avitm#26]
I didn't see a texts dataset as mentioned in the Readme.md. When I run:
nsgp = sklearn.datasets.fetch_20newsgroups()
result = pipeline.transform(nsgp)

I get the error below. I'm assuming it is because the model on GPU and data is on CPU? If so could you tell me how to collocate. Thx.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/sklearn/pipeline.py", line 451, in _transform
    Xt = transform.transform(Xt)
  File "/home/dg8965/pt-avitm/ptavitm/sklearn_api.py", line 85, in transform
    num_workers=0  # TODO causes a bug to change this on Mac
  File "/home/dg8965/pt-avitm/ptavitm/model.py", line 184, in predict
    output = model.encode(batch)
  File "/home/dg8965/pt-avitm/ptavitm/vae.py", line 115, in encode
    encoded = self.encoder(batch)
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/dg8965/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm

**Comment by vlukiyanov** [comment]
Shouldn't that be pipeline.transform(nsgp['data']) unless I'm misunderstanding https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html?

Does doing 
```
pipeline = make_pipeline(
    CountVectorizer(
        stop_words='english',
        max_features=2500,
        max_df=0.9
    ),
    ProdLDATransformer(cuda=False)
)
```
help?

Otherwise this might be a bug in the (somewhat kludged) sklearn-style API, I'll have a look. Thanks for spotting that and apologies for the slightly delayed reply!
